### ISSUE TITLE
Needs Example

### ISSUE THREAD

**Issue by UmangThapliyal** [Forecast-it/react-virtualized-dnd#5]
Hello, I was trying to use this library but I was stuck as there are no proper example and I faced some issues while trying to use it, I have mentioned conatinerHeight but still it shows this error can you help me.
![image](https://user-images.githubusercontent.com/34316267/61276204-302e8480-a7cd-11e9-8cbc-400518071e69.png)

**Comment by MagerlinC** [comment]
Hi there!
It's hard for me to debug your issue just seeing this. Were you able to get the Scrollbar and its contents to render (with a proper size)? Could you perhaps share how you implemented it?
I know it's probably just a typo, but just to make sure, the necessary prop is called containerHeight.

**Comment by FishwithCat** [comment]
great component !
will it support touch-action in mobile device ?

**Comment by UmangThapliyal** [comment]
> Hi there!
> It's hard for me to debug your issue just seeing this. Were you able to get the Scrollbar and its contents to render (with a proper size)? Could you perhaps share how you implemented it?
> I know it's probably just a typo, but just to make sure, the necessary prop is called containerHeight.

Sorry currently I have not working on the project where I was using and busy with other task will work on it sometimes next week and then will update

**Comment by jonatanalava** [comment]
@MagerlinC I have the same error. All I'm doing is defining my Droppable like this

`<Droppable droppableId="table" dragAndDropGroup="main" containerHeight={200}>`

**Comment by MagerlinC** [comment]
> @MagerlinC great component !
> will it support touch-action in mobile device ?
This is planned for a future update. Currently there are some issues with implementing this, but I'm aiming to release this in the future.

@jonatanalava it's hard to say without seeing the rest of your structure, but my guess would be that you're having sizing issues with either a parent or child container within the droppable. Usually putting a well-sized container around your droppable, and a col-flexing one inside does the job. Do you have some more code you could share?
